### ISSUE TITLE
What license terms change with new project identifiers?

### ISSUE THREAD

**Issue by joehand** [licensezero/licensezero-faq#16]
The project identifier seems crucial but there is not much in [the guide](https://guide.licensezero.com/#identifiers) about it. Since so much is dependent on the project identifier in the terms, perhaps more can be said about it in the guide. Specifically, this section jumped out at me:

> Private licenses last forever, and cover all contributions the developer makes with the same project identifier listed in the private license. Developers don’t promise to do any new work, or make it available under the same project identifier, by selling private licenses. That leaves developers in charge of what code gets covered by private licenses for specific project identifiers. If a developer embarks on a rewrite, or adds significant new functionality in a major release, they can define a new project identifier for that new work, and charge for private licenses to use it.

As far as I can tell the licenses don't set any terms as to when a project can be released under a new identifier. The pricing locks are an attempt to fix pricing for a specific time. But it all refers to "the project", which refers to the specific identifier not anything about the codebase. As I understand it, this means a developer could create a new UUID for every release (whether a bug fix or a major update) to get around the locks, correct?

I am intrigued by the idea of the project sponsors. But was looking to see if a Charity license ever "expired". It seems like changing the project identifier would be a way to expire Charity licenses. Cool!

**Comment by kemitchell** [comment]
This is excellent feedback. I will update the guide and mention!

The long story short here is that License Zero had to choose between locking developers into publishing future work as part of a single licensable project, allowing them to define licensable projects as they please, or setting rules about project scope that could become pretty complex.

The one hard and fast rule is that once you publish code with a project ID, you can’t take old work out of that project for folks who’ve already bought licenses. But developers have total freedom to start new projects for new work at almost any time.

As a side note: I really need to distinguish projects, in the sense of, say, dat CLI, and projects in the sense of one set of particular contributions to dat CLI, covered by a particular private license. “Project” is overloaded right now, and that’s causing confusion.

Maybe pick a different word?

**Comment by joehand** [comment]
> The long story short here is that License Zero had to choose between locking developers into publishing future work as part of a single licensable project, allowing them to define licensable projects as they please, or setting rules about project scope that could become pretty complex.

Makes sense! This could just bit a bit more clear.

> As a side note: I really need to distinguish projects, in the sense of, say, dat CLI, and projects in the sense of one set of particular contributions to dat CLI, covered by a particular private license. “Project” is overloaded right now, and that’s causing confusion.

Ya, agree project the word is part of the confusion. "Release" or "Version" may be a bit better but also perhaps overly specific. 

A larger part of the issue is that projects (in the broader sense) and sequential Project IDs are disconnected, e.g. you could easily visit a [project page](https://licensezero.com/projects/daf5a8b1-23e0-4a9f-a6c1-69c40c71816b) and buy a license without knowing that that Project ID is outdated if the developer did not revoke it. 

All of the website copy, guide, etc. speaks towards a singular "Project" and related license when usage may not reflect that. As a license buyer, whether project IDs are changed for each minor or major update would be a big difference and it'd be great to make sure sellers communicate this clearly.

**Comment by kemitchell** [comment]
I haven’t put enough time on this yet, but I have one decent candidate: “contribution set”.

A license covers a contribution set. One project—library, app, framework, whatever—may combine multiple contribution sets.

I haven’t heard the term before, so it might be fresh. The analogies to set theory are helpful, and don’t leak very much. Project as a union of contribution sets. For every contribution set you use, you need a corresponding license in your license set. And so on.

Again, just one candidate.

If we do adopt a new term, I’ll want to change the licensezero.json schema a bit, and CLI UI. But I anticipate eventually having to do that, whether I plan to or not.

**Comment by kemitchell** [comment]
@joehand, I've done a bit of work on the guide:

Private License Scope: <https://guide.licensezero.com/#private-license-scope>

Not Subscriptions: <https://guide.licensezero.com/#not-subscriptions>

I've also reviewed throughout to avoid confusing uses of "project".

**Comment by joehand** [comment]
Updates look great!

**Comment by kemitchell** [comment]
@joehand I'm going to call this closed, though there are a few follow-on items from it on my to-do list now.

In particular, `licensezero.json` entries still say `projectID`, which could be confusing. I'm not sure it's worth a schema change yet.

**Comment by kemitchell** [comment]
@joehand I forgot to mention: I also added a section on how licenses combine in dependency graphs: https://guide.licensezero.com/#license-graphs
