### ISSUE TITLE
Licenses need licenses

### ISSUE THREAD

**Issue by arei** [licensezero/licensezero-faq#17]
The licenses don't have a license. For example, can I take the parity license from Github, modify it slightly and use it in a slightly different form? What rights do I have with regards to the content of the licenses themselves? The licenses need licenses in and of themselves.

I’d love for this to be something super open like MIT but that’s your call.

**Comment by kemitchell** [comment]
@arei, you're right. There is no "license for the license" as yet.

License-licenses, which I've slipped into calling "meta licenses" here and there, are actually fairly rare in open software. GPL is locked down. The Apache Foundation has given permission to change their license, with attribution and respect for their name, but only on a separate webpage. Licenses from OSI, like OSL and AFL, address license-licensing directly.

Licensing the license texts themselves is on my list, but I think it's premature. I want the texts to stabilize a bit more, and having just renamed the public license options, to "Parity" and "Prosperity", I'd like to establish those names a bit more in the community.

In the meantime, are you interested in making a particular change? To which license?

**Comment by arei** [comment]
I’m thinking about using parity, but with a longer period then 32 days. I’m not suggesting a change on your part as I generally like 32 days, but I may want longer. This goes to my other ticket about letting the licensor set a variable length term, but a derivative friendly license supports the same thing.

Also, I may want to use parity without using the license zero application/agent stuff, but for a single word in the guide (“can” versus something like “must”) I’m not sure if I can do that under your terms/copyright.  As it stands right now, I don’t think I can because it’s not expressly allowed.

**Comment by kemitchell** [comment]
I've added `CHANGING` files to the repositories for each of the three public licenses: Parity, Prosperity, and Charity. The terms are analogous to permissive open source terms, with a condition that folks who make changes use a different name, or indicate that their version differs from the original.

https://github.com/licensezero/prosperity-public-license/commit/adc59e64b27b30d1d4a8297c89f7d55e25210493

https://github.com/licensezero/parity-public-license/commit/641573005930046a05de462c08f0b4d16a240f23

https://github.com/licensezero/charity-public-license/commit/68ba9f5ddff08502ef317b9ff88eb02d10e2d602

In your case, I think you may have meant that you'd like to use Prosperity---the noncommercial license---with a longer free-trial period. You are absolutely free to do so.  My conditions require that you remove the license title from your `LICENSE`, or do something like this:

```
The Prosperity Public License {{{version}}}
(Edited to lengthen the free-trial period under rule 1.)
```

Folks are _absolutely free_, _and encouraged_, to use Parity, Prosperity, and Charity without License Zero. Part of the rationale for the new license names was to avoid implying that they're only good in combination with licensezero.com. They work fine standing alone.

For example, the `licensezero` CLI is Charity-licensed.  And I plan to release the server code under Parity, without selling private licenses of any kind.
