### ISSUE TITLE
Wavers for projects?

### ISSUE THREAD

**Issue by Avi-D-coder** [licensezero/licensezero-faq#19]
Say library `A` was licensed under prosperity.
Project `B` was a open source project under a permissive licence like MIT, that wanted to use `A`.

How could the owner of `A` allow use by anyone using `A` only via `B` without requiring users of `B` to buy a licence for `A`?

If a waiver to a project was granted how could the sublicensing terms be enforced?

Essentially I'm asking how can a owner of a L0 property allow its use in select free or OSI software.

**Comment by kemitchell** [comment]
Have you seen https://paritylicense.com?

**Comment by Avi-D-coder** [comment]
I have. My primary concern is along the lines of [enforceability](https://www.processmechanics.com/2018/10/18/the-server-side-public-license-is-flawed/).  From a layman's perspective parity seems similar to SSPL and while I couldn't say if the arguments against SSPL are sound, the backlash makes me uneasy about licenses in this category.

That's why I was wondering about more fine grain exceptions to prosperity, for all I know what I'm asking about could be more legally dubious?

**Comment by kemitchell** [comment]
I know and respect Van. We’ve gone back and forth privately about his copyright misuse theory before.

If I’m not mistaken, I’ve yet to read another US lawyer who shares Van’s view on misuse. Several posted comments to the OSI thread for SSPL addresses the topic when I was still subscribed to that list.

**Comment by kemitchell** [comment]
@avi-d-coder, I want to make sure you didn’t feel like I was shutting this issue down!

Whether it’s here with you or by email with Van, I’m happy to talk enforceability and the limits of new copyleft licenses with anyone who’s genuinely interested. That goes for not just Parity, but other efforts like Van’s super interesting Ceyptographic Autonomy License, as well.

The thing I definitely _don’t_ want to do is rely on appeal to authority or strength in numbers, especially when making points to those who probably don’t feel “legally qualified”. So I shouldn’t have written anything that could be read to imply that Van’s blog post can be ignored as an outlier. I shouldn’t have elided details that Van and I have discussed on our own.

**Comment by Avi-D-coder** [comment]
I appreciate your concern. I  didn't feel you were shutting down the issue.

The details of the  disagreement/dialogue would be enlightening reading.
