### ISSUE TITLE
Should licensezero.com support counting private license fees against relicense sponsorship prices?

### ISSUE THREAD

**Issue by kemitchell** [licensezero/licensezero-faq#2]
Under an assurance contract model, private license fees would add up until they reach a threshold set by the developer, at which point the project would be automatically relicensed on permissive terms.

At present, sponsoring relicensing means paying a specific, separate price, no matter how many others have paid for private licenses in the past.

**Comment by joehand** [comment]
Yes! I'd also be interested in allowing a developer to mark a project as sponsored based on a total amount of donations from another platform such as OpenCollective or Patreon.

**Comment by kemitchell** [comment]
Developers can already relicense their projects at will. They can change to Charity terms, or to any other license, for that matter. The only L0 requirement is that they also retract their project from sale through licensezero.com, so people don’t keep buying private licenses when they don’t need them.

Developers are also free to make offers and public commitments about relicensing elsewhere, such as through cloudfunding platforms. But License Zero doesn’t publish those commitments or sign terms on behalf of the developers to seal those deals. License Zero only brokers relicensing deals on its standard form, through project pages and the CLI.

The question I meant to pose here was a little narrower. If Adam buys a private license for Jane’s project at $10, and Jane offers to relicense her project through the API for $100, should Adam pay $90 instead of $100?

This was a little more relevant when License Zero was set up to sell site licenses to companies. Now that License Zero only sells private licenses to individual people, it matters a lot less.

**Comment by kemitchell** [comment]
I think the right answer to my original question is a "no", since the complexity in implementation would far outweigh the likely benefit.
