### ISSUE TITLE
invalid jurisdiction: DE-BY

### ISSUE THREAD

**Issue by juliangruber** [licensezero/licensezero-faq#5]
`DE-BY` is the ISO 3116 code for where I'm living, see https://en.wikipedia.org/wiki/Bavaria.

Are non-US countries not supported yet?

**Comment by kemitchell** [comment]
Looking at this now. German jurisdictions should definitely be supported!

**Comment by kemitchell** [comment]
PS: I plan to make the source for the server available fairly soon. This kind of thing should become much easier to deal with then. Thanks for taking the time to find a place to open an issue.

**Comment by kemitchell** [comment]
Ah. So it turns out this is an issue in the CLI. I will open an issue there shortly, and link it.

**Comment by kemitchell** [comment]
`npm i -g "licensezero@1.0.0-pre-14"` should do it for you.

Thanks again for this issue, @juliangruber. 

Basically, early-early versions of both CLI and server supported US only, just as a placeholder. I eventually went back and did a proper list of jurisdictions for the server, but forgot to put that list in the CLI, too. Now the list is in <https://www.npmjs.com/package/licensezero-jurisdictions>.
