### ISSUE TITLE
Can I do this as an individual or do I need a company?

### ISSUE THREAD

**Issue by cristim** [licensezero/licensezero-faq#6]
I am a full time employee and I maintain an open source project in my spare time.

My project could be monetized with licensezero maybe enough to pay some of the bills for a while but maybe not enough to make a living on the long term.

Do I need to be registered as freelancer or to have a company in order to collect these payments? Because the benefits are small I would prefer not to register, I will surely declare this income and pay my taxes as an individual but I don't think it makes sense to go through the bureaucratic hurdles of running a consultancy for this.

**Comment by kemitchell** [comment]
@cristim some of these are legal questions about your personal situation. I can't answer those for you.

I _can_ point out that all License Zero requires to get started is a Stripe account. Both individuals and businesses with Stripe accounts can use License Zero to sell licenses. But I expect the vast majority will be individuals without any kind of company or other business entity.

**Comment by cristim** [comment]
Thanks @kemitchell I'll give it a try soon.

**Comment by otisg** [comment]
> maybe enough to pay some of the bills for a while but maybe not enough to make a living on the long term.

Maybe you should sell your services.  Help companies integrate this into their infra.

**Comment by cristim** [comment]
@otisg I would prefer to spend my time coding to make it just work and bug free instead of doing customer support. I offered paid support for a lot of time but nobody asked for it because the software pretty much just works already
