### ISSUE TITLE
Should License Zero drop support for the noncommercial license?

### ISSUE THREAD

**Issue by kemitchell** [licensezero/licensezero-faq#9]
Thinking to print for a moment...

Pros of supporting a noncommercial license:
- gives licensors choice
- addresses the source of a lot frustration---relations with for-profit forms---directly
- clear prior art in Creative Commons' NC licenses

Cons of supporting a noncommercial license:
- the noncommercial license is clearly _not_ an open source software license, according to most folks' reasoned definitions
- the strongest concerns I've heard from the community concern the noncommercial license, many born out of experience with CC-NC licenses
- the current draft NC license adopts, rather than improves, the CC license ambiguity about what is and is not commercial use

I've come to see a difference in values---open source or not---as the fundamental source of tension that License Zero is trying to redress. That tension tends to manifest as indie maintainer versus for-profit company, in most indie devs' experiences. But I think that's correlation, not causation. I see bad community-company relations as symptomatic of company's preference for closed, proprietary business models. Some for-profit companies release their "crown jewels" as open source. Not enough, but some. And that ought to be encouraged, not written off as a small leak in an overall abstraction of open source and where it belongs.

So far, I've stuck to supporting both noncommercial and reciprocal public licenses, mostly because I weight the pro of developer choice very high. But as I see support for the noncommercial license coloring perception of the project as a whole, and complicating explanations---_which_ kind of License Zero project is this one?---I'm opening up more and more to focusing solely on the reciprocal license.

**Comment by ghost** [comment]
I see the recriprocal and NC licenses as useful in different situations. It might be hard to otherwise get companies to pay for professional tools that are developed in the open but used as-is instead of extended as a library.

**Comment by kemitchell** [comment]
@substack that is absolutely the biggest substantive difference between the two licenses as they stand now. And I really don't think I can write a license with that functionality that falls under any common, terms-based definition of "open source". Even if we ignore OSI and OSD. Even if we ignore the free software definition.

I suppose the next question is, seeing that's the case, is it worthwhile to support licensing NC software through License Zero as a system? CLI. Licensing web service. Documentation. It's all done, so that cost is zero, though there'll be maintenance going forward, I'm sure. It really boils down to the complexity of explaining that devs have the option, and making sure to explain the effects of choosing each public license.

To be practical again, frankly, if you have a project in mind for L0-NC, I'm going to support it. I've retained it this far precisely in the spirit of giving the option to devs, in case they see things differently than I do, or want to experiment for the sake of giving things a try. I'm making a lot of choices for the sake of standardization and administrability. But when it comes down to it, this project is still about giving devs tools and seeing what they do with them. That won't change.

**Comment by kemitchell** [comment]
My friend and colleague @tieguy was kind enough to [tweet about this issue](https://twitter.com/luis_in_140/status/955198835747254272):

> "open source or not"—be more specific? open source licenses as defined by OSD? open source collaborative (community?) development as practiced in 2018? In the late 90s?

Throughout the post above, I'm using open source loosely, and intentionally so, along lines explored in [some earlier writing of mine](https://writing.kemitchell.com/2016/05/13/What-Open-Source-Means.html). "Open source" as in the community that exists online, and the way it works, largely in ignorance or indifference to OSD and the free software definition. A community, its process, and its values, not is outputs.

I owe myself a post on the OSI process and OSD, for sure. But not here.

**Comment by ghost** [comment]
I do have a project in mind that I think would be a good fit for NC and several that would be a good fit for reciprocal licenses. Product development is hard and takes time, especially while juggling some other gigs, but I've been making good progress lately and intend to push these to a useful state.

Thanks for coming up with these licenses. I'm looking forward to being able to spend more time directly working on libraries and open end-user tools and less on contracts.

**Comment by kemitchell** [comment]
@substack: ACK

I may revisit this later. But for now, the answer to "Should License Zero drop support for the noncommercial license?" is "no".

**Comment by kemitchell** [comment]
@substack, not sure how much to take from it, but here's an old graph from some research on the popularity of various CC licenses:

https://wiki.creativecommons.org/wiki/File:Licenses-pie-20060613.png

-NC- variants are far more popular than I would have imagined.

**Comment by kemitchell** [comment]
Interesting [population study on the use of various Creative Commons licenses](https://stateof.creativecommons.org/data-and-acknowledgements-page/):

> The circles showing percentages by CC license and PD tools correspond to the following numbers which include Google data (web pages linking to current tools plus retired PD tool) and data from platforms not cached by Google (where we know the breakdown of works by license).
> 
> ...
> 
> Breakdown by license: Google + Platforms not cached by Google = Total estimated works under that license
> 
> Google + Platforms not cached by Google
> 
> CC BY (19.9%): 56,830,000 + 164,964,864 = 221,794,864
> CC BY-SA (37.3%): 72,310,000 + 342,940,213 = 415,250,213
> CC BY-ND (2.4%): 3,660,000 + 22,757,202  = 26,417,202
> CC BY-NC (5.6%): 11,680,000 + 50,709,522 = 62,389,522
> CC BY-NC-SA (12.8%): 33,770,000 + 108,413,540 = 142,183,540
> CC BY-NC-ND (13.6%): 41,400,000 + 109,495,107 = 150,895,107
> Public domain total (8.4%): 23,030,000 + 69,955,089 = 92,985,089
> CC0 (6.4%): 4,400,000 + 67,002,743 = 71,402,743
> PDM (0.3%): 820,000 + 2,952,346 = 3,772,346
> Retired PD tool (1.6%): 17,810,000
> Retired tools total (0.002%):
> Sampling+: 20,000
>
> Total Free Culture works (CC BY + CC BY-SA + Public domain): 730,030,166 (65.7%). CC uses the definition of free cultural works at Freedom Defined to categorize the CC licenses. “Free Culture” licenses allow for both commercial use and adaptations. Learn more at http://creativecommons.org/freeworks.
